package lexer

var Functions map[string]int = map[string]int{
	"ADDDATE":      ADDDATE_SYM,
	"BIT_AND":      BIT_AND,
	"BIT_OR":       BIT_OR,
	"BIT_XOR":      BIT_XOR,
	"CAST":         CAST_SYM,
	"COUNT":        COUNT_SYM,
	"CURDATE":      CURDATE,
	"CURTIME":      CURTIME,
	"DATE_ADD":     DATE_ADD_INTERVAL,
	"DATE_SUB":     DATE_SUB_INTERVAL,
	"EXTRACT":      EXTRACT_SYM,
	"GROUP_CONCAT": GROUP_CONCAT_SYM,
	"MAX":          MAX_SYM,
	"MID":          SUBSTRING, /* unireg function */
	"MIN":          MIN_SYM,
	"NOW":          NOW_SYM,
	"POSITION":     POSITION_SYM,
	"SESSION_USER": USER,
	"STD":          STD_SYM,
	"STDDEV":       STD_SYM,
	"STDDEV_POP":   STD_SYM,
	"STDDEV_SAMP":  STDDEV_SAMP_SYM,
	"SUBDATE":      SUBDATE_SYM,
	"SUBSTR":       SUBSTRING,
	"SUBSTRING":    SUBSTRING,
	"SUM":          SUM_SYM,
	"SYSDATE":      SYSDATE,
	"SYSTEM_USER":  USER,
	"TRIM":         TRIM,
	"VARIANCE":     VARIANCE_SYM,
	"VAR_POP":      VARIANCE_SYM,
	"VAR_SAMP":     VAR_SAMP_SYM,
}
